

CREATE TABLE LOGIN(
username NVARCHAR (10),
pass NVARCHAR (10),
)

CREATE TABLE BOUGHTBYY(
SSN INT,
ARTNO INT,
purchase_date DATETIME,
qty INT,
SSN_artist INT,)

INSERT INTO LOGIN VALUES ('sara','1234')
INSERT INTO LOGIN VALUES ('alabed','12345')

ALTER TABLE BOUGHTBYY ADD sold_price INT
DELETE FROM ARTWORK
SELECT * FROM ARTWORK
DROP TABLE LOGIN

