CREATE TABLE BOUGHTBY(
SSN INT,
ARTNO INT,
purchase_date DATETIME,
qty INT,
PRIMARY KEY (SSN,ARTNO,purchase_date))

SELECT * FROM CUSTOMER
ALTER TABLE BOUGHTBY ADD 
FOREIGN KEY (ARTNO) REFERENCES ARTWORK(ARTNO);


ALTER TABLE BOUGHTBY ADD 
FOREIGN KEY (SSN) REFERENCES CUSTOMER(SSN);
