INSERT INTO ARTWORK VALUES(1,'///',2020,'DIGITAL',10000,20000,'All Styles',NULL,100)
INSERT INTO ARTWORK VALUES(2,'///',2020,'DIGITAL',15000,25000,'Cartoon',NULL,102)
INSERT INTO ARTWORK VALUES(3,'///',2020,'DIGITAL',20000,40000,'All styles',NULL,100)


DELETE FROM BOUGHTBY
INSERT INTO BOUGHTBY VALUES(1,1,'2020-04-21 10:12:22 AM',3,100)
INSERT INTO BOUGHTBY VALUES(2,1,'2020-04-21 10:20:20 AM',4,100)
INSERT INTO BOUGHTBY VALUES(2,2,'2020-04-21 10:20:20 AM',3,102)


INSERT INTO ARTIST VALUES(100,'Sara','Beirut',19,71228720,'@','All styles')
INSERT INTO ARTIST VALUES(102,'Huda','AL Ghaziye',19,712563,'@','Cartoon')
INSERT INTO ARTIST VALUES(103,'Dalia','Saida',18,72355720,'@','Realism')

--OVER ALL TOTAL QUERY
SELECT SUM(selling_price*qty) FROM BOUGHTBY
INNER JOIN ARTWORK ON BOUGHTBY.ARTNO=ARTWORK.ARTNO

SELECT SUM(selling_price*qty) FROM ARTWORK
INNER JOIN ARTWORK ON BOUGHTBY.ARTNO=ARTWORK.ARTNO

DROP TABLE BOUGHTBY
DROP TABLE ARTWORK

CREATE TABLE ARTWORK(
ARTNO INT,
title NVARCHAR (30),
Year_made INT,
type_art NVARCHAR (20),
original_price INT,
selling_price INT,
art_style NVARCHAR(20),
art_image IMAGE,
PRIMARY KEY (ARTNO))


CREATE TABLE BOUGHTBYY(
SSN INT,
ARTNO INT,
purchase_date DATETIME,
qty INT,
SSN_artist INT,)

ALTER TABLE BOUGHTBY ADD SSN_ARTIST INT
FOREIGN KEY (SSN_ARTIST) REFERENCES ARTIST(SSN);
ALTER TABLE BOUGHTBY ADD FOREIGN KEY (ARTNO) REFERENCES ARTWORK(ARTNO);

ALTER TABLE ARTWORK ADD SSN INT;
ALTER TABLE ARTWORK ADD FOREIGN KEY (SSN) REFERENCES ARTIST(SSN)










CREATE TABLE LOGIN(
username NVARCHAR (10),
password NVARCHAR (10),
)
