CREATE TABLE BOUGHTBY(
SSN INT,
ARTNO INT,
purchase_date DATETIME,
qtY INT,
PRIMARY KEY (SSN,ARTNO,purchase_date))

ALTER TABLE BOUGHTBY ADD FOREIGN KEY (SSN) REFERENCES CUSTOMER(SSN);
ALTER TABLE BOUGHTBY ADD FOREIGN KEY (ARTNO) REFERENCES ARTWORK(ARTNO);

